### ISSUE TITLE
CLI morph_hybrid_align_tokens command problem

### ISSUE THREAD

**Issue by yuvaly95** [OnlpLab/NEMO#13]
Hi, I'm having a problem running the `morph_hybrid_align_tokens` command after pulling the changes made to the repository.
While running other commands such as `morph_hybrid` do work on the input files attached, the command `python nemo.py morph_hybrid_align_tokens morph NER_TEST.txt NER_RESULT.txt` produces the following message:

```  File "nemo.py", line 360, in run_morph_hybrid
    new_toks = get_fixed_tok(temp_morph_ner_output_path, orig_sents=prun_sents)
  File "nemo.py", line 224, in get_fixed_tok
    new_toks = bclm.get_token_df(new_sents, fields=['bio'])
  File "C:\Users\Tmuna\anaconda3\envs\nemoenv\lib\site-packages\bclm\transforms.py", line 70, in get_token_df
    tok_df = tok_df.sort_index().reset_index()
  File "C:\Users\Tmuna\anaconda3\envs\nemoenv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Tmuna\anaconda3\envs\nemoenv\lib\site-packages\pandas\core\frame.py", line 5794, in reset_index
    new_obj.insert(0, name, level_values)
  File "C:\Users\Tmuna\anaconda3\envs\nemoenv\lib\site-packages\pandas\core\frame.py", line 4409, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert token_str, already exists
```
the temporary files for NER_TEST_2.txt are also attached.
[temp.zip](https://github.com/OnlpLab/NEMO/files/7078151/temp.zip)
[NER_TEST.txt](https://github.com/OnlpLab/NEMO/files/7078212/NER_TEST.txt)
[NER_TEST_2.txt](https://github.com/OnlpLab/NEMO/files/7078213/NER_TEST_2.txt)

**Comment by cjer** [comment]
I don't really see why this would happen. Again, I just ran the same command and input and it worked well. 
What version of `bclm` do you have in the env?
Try to `pip install bclm --upgrade` and see if this changes anything.

**Comment by cjer** [comment]
I generally recommend for now that you switch to use the API instead, it has the same commands, but it's faster, gives you much better info back, and easier to debug. I plan to sometime have `nemo.py` use the code used in the API endpoints for the same reasons (and to avoid the current code duplication).

**Comment by yuvaly95** [comment]
I'm running `bclm 1.0.2`.
O.k I'll try using the API, thanks!

**Comment by cjer** [comment]
Great :) 
Then I'll close this one for now. If you do get back to, it feel free to reopen.
