### ISSUE TITLE
YAP_API_URL, YAP_API_HEADERS 

### ISSUE THREAD

**Issue by dudio92** [OnlpLab/NEMO#3]
Those variables doesn't seem to be declared anywhere in the project, and cannot be found at config.py.

Thanks :)

**Comment by cjer** [comment]
Both are declared in config.py, make sure you checkout the api branch if you're trying to run api_main.py

https://github.com/OnlpLab/NEMO/blob/api/config.py#L23

**Comment by dudio92** [comment]
*FACEPALM*

Thanks.
